import type { LotteryConfig, LotteryType } from "./types";

export const LOTTERY_CONFIG: Record<LotteryType, LotteryConfig> = {
  mega645: {
    type: "mega645",
    name: "Mega 6/45",
    sourceUrl: "https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power645.jsonl",
    maxNumber: 45,
    pickCount: 6,
    hasBonus: false,
    drawDays: [3, 5, 7],
    sourceFormat: "json",
    resultSelectorMap: {
      date: "regex:Ngày quay số.*?(\\d{2}/\\d{2}/\\d{4})",
      numbers: "regex:(?:\\b\\d{1,2}\\b(?:\\s*[-,;|]\\s*\\b\\d{1,2}\\b){5,})",
      jackpot: "regex:Jackpot.*?(\\d[\\d.,]*)",
      rows: ".table tr",
    },
    notes: "Dữ liệu JSONL từ vietvudanh/vietlott-data.",
  },
  power655: {
    type: "power655",
    name: "Power 6/55",
    sourceUrl: "https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power655.jsonl",
    maxNumber: 55,
    pickCount: 6,
    hasBonus: true,
    bonusName: "specialNumber",
    drawDays: [2, 4, 6],
    sourceFormat: "json",
    resultSelectorMap: {
      date: "regex:Ngày quay số.*?(\\d{2}/\\d{2}/\\d{4})",
      numbers: "regex:(?:\\b\\d{1,2}\\b(?:\\s*[-,;|]\\s*\\b\\d{1,2}\\b){5,})",
      specialNumber: "regex:Power 6/55.*?\\b(\\d{1,2})\\b\\s*$",
      jackpot1: "regex:Giải Jackpot 1.*?(\\d[\\d.,]*)",
      jackpot2: "regex:Giải Jackpot 2.*?(\\d[\\d.,]*)",
      rows: ".table tr",
    },
    notes: "Dữ liệu JSONL từ vietvudanh/vietlott-data, có số đặc biệt.",
  },
  power535: {
    type: "power535",
    name: "Power 5/35",
    sourceUrl: "https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power535.jsonl",
    maxNumber: 35,
    pickCount: 5,
    hasBonus: false,
    drawDays: [1, 2, 3, 4, 5, 6, 7],
    sourceFormat: "json",
    resultSelectorMap: {
      date: "regex:(\\d{2}/\\d{2}/\\d{4})",
      numbers: "regex:(?:\\b\\d{1,2}\\b(?:\\s*[-,;|]\\s*\\b\\d{1,2}\\b){4,})",
      rows: ".table tr",
    },
    notes: "Dữ liệu JSONL từ vietvudanh/vietlott-data.",
  },
  max3d: {
    type: "max3d",
    name: "Max 3D",
    sourceUrl: "https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/3d.jsonl",
    maxNumber: 10,
    pickCount: 3,
    hasBonus: false,
    drawDays: [2, 4, 6],
    sourceFormat: "json",
    resultSelectorMap: {
      date: "regex:Ngày quay số.*?(\\d{2}/\\d{2}/\\d{4})",
      numbers: "regex:(?:\\b\\d{1,2}\\b(?:\\s*[-,;|]\\s*\\b\\d{1,2}\\b){2,})",
      rows: ".table tr",
    },
    notes: "Dữ liệu 3D có cấu trúc giải riêng, chưa dùng trong import mặc định.",
  },
  keno: {
    type: "keno",
    name: "Keno",
    sourceUrl: "https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/keno.jsonl",
    maxNumber: 80,
    pickCount: 10,
    drawCount: 20,
    hasBonus: false,
    drawDays: [1, 2, 3, 4, 5, 6, 7],
    sourceFormat: "json",
    resultSelectorMap: {
      date: "regex:(\\d{2}/\\d{2}/\\d{4})",
      numbers: "regex:(?:\\b\\d{1,2}\\b(?:\\s*[-,;|]\\s*\\b\\d{1,2}\\b){19,})",
    },
    notes: "Keno quay 20 số từ 1-80, mỗi ngày nhiều kỳ. pickCount=10 là số cược của người chơi.",
  },
};

export const LOTTERY_TYPES = Object.keys(LOTTERY_CONFIG) as LotteryType[];
